# Site Settings
title: My Resume
url: 'https://kevinallioli.com'
baseurl: '' #change it according to your repository name

style: styles-aws

#Profile information
name: Alan Doe
tagline: AWS Solutions Architect
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'
#language button

lang-en: en.png
lang-en-url: https://kevinallioli.com
lang-es: es.png
lang-es-url: https://kevinallioli.es
lang-fr: fr.png
lang-fr-url: https://kevinallioli.fr

#sidebar links
email: hello@linit.io
phone:  012 345 6789
website: www.linit.io
linkedin: kevinallioli
github: kallioli
twitter: '@kevinallioli'
#Update all the sections by editing the files inside _data folder.

resume-file: #Put here the full file name (with extention) of your resume file (myresume.pdf)

# Tracker
analytics: UA-69289145-4

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
